### ISSUE TITLE
Promotion image in homepage does not show

### ISSUE THREAD

**Issue by ronnapatp** [Kumi-the-chubby-bear/New-KumiWeb#26]
![image](https://user-images.githubusercontent.com/84321166/133374187-03d560e0-f40d-43f8-8cd5-a5a7cb021c98.png)

**Comment by ronnapatp** [comment]
@deedee2110 Fix pls

**Comment by ronnapatp** [comment]
You need to download image and put in public/promotion-image
also rename to promotion name
-Thanks-
Pie

**Comment by deedee2110** [comment]
Electroboom has fixed
